mindsearch/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from mindsearch.extensions import bcrypt
from mindsearch.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class User(UserMixin, SurrogatePK, Model):

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

mindsearch/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

mindsearch/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template

from mindsearch.settings import ProdConfig
from mindsearch.assets import assets
from mindsearch.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar
)
from mindsearch import public, user


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

mindsearch/user/__init__.py
'''The user module.'''

from . import views

mindsearch/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask.ext.login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

mindsearch/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

mindsearch/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© David Y. Zhang</li>
  </ul>

    <ul class="footer-nav">
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
  </small>
</footer>

mindsearch/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    Mindsearch

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with login_form=login_form %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

mindsearch/templates/nav.html
<!--Params: login_form: LoginForm object-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      Mindsearch

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% set show_login = false %}
    {% if show_login %}
      {% if current_user and current_user.is_authenticated() %}
      <ul class="nav navbar-nav navbar-right">
          <li>
              <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
          </li>
          <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

      </ul>
      {% elif login_form %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('public.register') }}">Create account</a></li>
      </ul>
      <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
        {{ login_form.hidden_tag() }}
        <div class="form-group">
          {{ login_form.username(placeholder="Username", class_="form-control") }}
          {{ login_form.password(placeholder="Password", class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-default">Log in</button>
      </form>
      {% endif %}
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

mindsearch/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}